config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  get 'events/index'

  resources :users
  resources :events do
    get 'rsvp'
  end

  root "events#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    #has_many :users
    has_many :rsvps, foreign_key: :attended_event_id
    has_many :attendees, through: :rsvps

    validates :title, presence: true
    validates :date, presence: true
    validates :location, presence: true

    scope :past, -> { where('date < ?', DateTime.now) }
    scope :future, -> { where('date > ?', DateTime.now) }
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  has_many :rsvps, foreign_key: :attendee_id
  has_many :attended_events, through: :rsvps

  validates :username, presence: true, uniqueness: true, length: { in: 2..12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        attributes = [:username, :email]
        devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
        devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    #@event = Event.new(event_params)
    #@event.creator = current_user    #build_association alternatate method tried here
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  def rsvp
    @event = Event.find(params[:event_id])
    if @event.attendees.include?(current_user)
      redirect_to @event
    else
      @event.attendees << current_user
      redirect_to @event
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :location)
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
    end

    def new
        @user = User.new
    end
 
    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to posts_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    #def show
    #    @user = User.find(params[:id])
    #end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:email,:username,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Home</h1>

<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

<% if user_signed_in? %>
  <%= link_to "View profile", users_path %>
<% end %>

<h2>All current events:</h2>
<ul>
    <% @events.future.each do |event| %>
      <li>
          <%= link_to event.title, event %>
      </li>
    <% end %>
</ul>

<%= link_to "Create a new event", new_event_path %>

<h4>Past events:</h4>
<ul>
    <% @events.past.each do |event| %>
      <li>
          <%= link_to event.title, event %>
      </li>
    <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %><br>
    <% @event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p><%= @event.date%></p>

<p><%= @event.location%></p>

<% if current_user.id == @event.creator.id %>
    <%= link_to "Delete event", event_path(@event), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } 
    %>
<% end %>

<ul>
    <% @event.attendees.each do |user| %>
            <li>
                <%= user.username %>
            </li>
    <% end %>
</ul>

<% if current_user.id == @event.creator.id %>
    <p> </p>
<% else %>
    <%= link_to "Attend this event", event_rsvp_path(@event.id) %>
<% end %>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Your profile</h1>


<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

<h3>Events you've created</h3>
<ul>
    <% @user.created_events.each do |event| %>
      <li>
          <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
</ul>

<h3>Events you're attending</h3>
<ul>
    <% @user.attended_events.each do |event| %>
      <% if event.date.future? %>
        <li>
            <%= link_to event.title, event_path(event) %>
        </li>
      <% end %>
    <% end %>
</ul>

<h4>Previous events you've attended</h4>
<ul>
    <% @user.attended_events.each do |event| %>
      <% if event.date.past? %>
        <li>
            <%= link_to event.title, event_path(event) %>
        </li>
      <% end %>
    <% end %>
</ul>


<%= link_to "Create a new event", new_event_path %>
<%= link_to "Home", root_path %>